[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework = arduino
monitor_speed = 115200

build_flags = 
    -I src/Sensores
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_ldf_mode = deep+
lib_deps =
    SPI
    Wire
  