[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM7
monitor_speed = 115200
build_flags = -I src/Sensores
lib_ldf_mode = deep+
lib_deps =
    SPI
    Wire
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/RTClib @ ^2.1.4